-- SafeBase schema (Postgres + pgvector, no Supabase Auth / RLS)

create extension if not exists "pgcrypto";
create extension if not exists vector;

-- ---------------------------------------------------------------------------
-- Users (replaces auth.users)
-- ---------------------------------------------------------------------------

create table public.users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  email text not null,
  password_hash text not null,
  created_at timestamptz not null default now(),
  constraint users_username_unique unique (username),
  constraint users_email_unique unique (email)
);

create index users_created_at_idx on public.users (created_at desc);

-- ---------------------------------------------------------------------------
-- Business tables
-- ---------------------------------------------------------------------------

create table public.profiles (
  user_id uuid not null primary key references public.users (id) on delete cascade,
  content text not null default '# 核心画像
尚未生成

## 触发清单
尚未记录

## 资源库
尚未记录',
  updated_at timestamptz not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  embedding vector(2048),
  created_at timestamptz not null default now()
);

create index messages_user_created_idx on public.messages (user_id, created_at desc);

create table public.diaries (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  title text not null default '',
  content text not null default '',
  embedding vector(2048),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index diaries_user_updated_idx on public.diaries (user_id, updated_at desc);

create table public.summaries (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  type text not null check (type in ('daily', 'weekly', 'monthly', 'yearly')),
  content text not null,
  summary_date date not null,
  embedding vector(2048),
  created_at timestamptz not null default now(),
  constraint uq_summary_user_type_date unique (user_id, type, summary_date)
);

create index summaries_user_date_idx on public.summaries (user_id, summary_date desc);

create table public.anchors (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  event_name text not null,
  initial_thought text,
  current_thought text,
  evolution_history jsonb not null default '[]'::jsonb,
  embedding vector(2048),
  updated_at timestamptz not null default now()
);

create index anchors_user_id_idx on public.anchors (user_id);

create table public.data_access_audit (
  id bigint generated always as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid references public.users (id) on delete set null,
  subject_user_id uuid not null references public.users (id) on delete cascade,
  op text not null check (op in ('SELECT', 'INSERT', 'UPDATE', 'DELETE')),
  schema_name text not null default 'public',
  table_name text not null,
  row_pk text,
  detail jsonb not null default '{}'::jsonb
);

create index data_access_audit_subject_time_idx
  on public.data_access_audit (subject_user_id, occurred_at desc);

-- ---------------------------------------------------------------------------
-- Vector indexes (best-effort)
-- ---------------------------------------------------------------------------

do $$ begin
  create index messages_embedding_hnsw_idx
    on public.messages using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64) where embedding is not null;
exception when others then
  raise notice 'messages HNSW skipped: %', sqlerrm;
end $$;

do $$ begin
  create index diaries_embedding_hnsw_idx
    on public.diaries using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64) where embedding is not null;
exception when others then
  raise notice 'diaries HNSW skipped: %', sqlerrm;
end $$;

do $$ begin
  create index summaries_embedding_hnsw_idx
    on public.summaries using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64) where embedding is not null;
exception when others then
  raise notice 'summaries HNSW skipped: %', sqlerrm;
end $$;

do $$ begin
  create index anchors_embedding_hnsw_idx
    on public.anchors using hnsw (embedding vector_l2_ops)
    with (m = 16, ef_construction = 64) where embedding is not null;
exception when others then
  raise notice 'anchors HNSW skipped: %', sqlerrm;
end $$;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger diaries_set_updated_at
  before update on public.diaries
  for each row execute function public.set_updated_at();

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create trigger anchors_set_updated_at
  before update on public.anchors
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RAG RPCs (explicit user_id — backend passes JWT subject)
-- ---------------------------------------------------------------------------

create or replace function public.get_recent_memory_messages(
  p_user_id uuid,
  msg_limit int default 30
)
returns table (role text, content text)
language sql
stable
as $$
  with recent as (
    select m.role, m.content, m.created_at
    from public.messages m
    where m.user_id = p_user_id
    order by m.created_at desc
    limit greatest(1, least(msg_limit, 100))
  )
  select recent.role, recent.content
  from recent
  order by recent.created_at asc;
$$;

create or replace function public.match_summaries_daily(
  p_user_id uuid,
  query_embedding vector(2048),
  match_count int default 2
)
returns table (summary_date date, content text)
language sql
stable
as $$
  select s.summary_date, s.content
  from public.summaries s
  where s.user_id = p_user_id
    and s.type = 'daily'
    and s.embedding is not null
  order by s.embedding <-> query_embedding
  limit greatest(0, least(match_count, 10));
$$;

create or replace function public.match_anchors(
  p_user_id uuid,
  query_embedding vector(2048),
  match_count int default 1
)
returns table (
  event_name text,
  initial_thought text,
  current_thought text
)
language sql
stable
as $$
  select a.event_name, a.initial_thought, a.current_thought
  from public.anchors a
  where a.user_id = p_user_id
    and a.embedding is not null
  order by a.embedding <-> query_embedding
  limit greatest(0, least(match_count, 10));
$$;

create or replace function public.match_diaries(
  p_user_id uuid,
  query_embedding vector(2048),
  match_count int default 2
)
returns table (id bigint, title text, content text, updated_at timestamptz)
language sql
stable
as $$
  select d.id, d.title, d.content, d.updated_at
  from public.diaries d
  where d.user_id = p_user_id
    and d.embedding is not null
  order by d.embedding <-> query_embedding
  limit greatest(0, least(match_count, 10));
$$;
